import React, { useState, useEffect, useCallback, useMemo, memo, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Image,
  Alert,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  TextInput,
  Platform,
  FlatList,
  RefreshControl,
  GestureResponderEvent,
} from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { PanGestureHandler, State } from 'react-native-gesture-handler';
import { useRouter } from 'expo-router';
import * as Location from 'expo-location';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { supabase } from '../../lib/supabase';
import { SwipeDishPayload } from '../../lib/swipes';
import { useFavorites } from '../../context/FavoritesContext';
import { MaterialIcons } from '@expo/vector-icons';

type Dish = SwipeDishPayload & {
  price?: number | null;
};

const DEFAULT_IMAGE_URL = 'https://placehold.co/600x400?text=Dish';

function imagePublicUrl(path: string | null): string | undefined {
  if (!path) {
    return undefined;
  }

  // When dishes are generated by the loader, the `image_url` column is stored as a
  // full, publicly accessible URL. Older records might still contain the original
  // storage path though, so we normalise both cases here.
  if (/^https?:\/\//i.test(path)) {
    return path;
  }

  const { data } = supabase.storage.from('dish-images').getPublicUrl(path);
  return data?.publicUrl || undefined;
}

// No need to populate restaurant names - just use what's in the database

export default function FoodFinder() {
  const [dishes, setDishes] = useState<Dish[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [activeQuery, setActiveQuery] = useState('');
  const [hasInitiatedSearch, setHasInitiatedSearch] = useState(false);
  const [refreshing, setRefreshing] = useState(false);

  // Location state
  const [userLocation, setUserLocation] = useState<{ latitude: number; longitude: number; name?: string } | null>(null);
  const [locationPermission, setLocationPermission] = useState<'granted' | 'denied' | 'undetermined'>('undetermined');
  const [manualLocation, setManualLocation] = useState('');
  const [showLocationInput, setShowLocationInput] = useState(false);

  // Distance selector state
  const [searchDistance, setSearchDistance] = useState<number>(3); // Default 3 miles
  const [showDistanceDropdown, setShowDistanceDropdown] = useState(false);

  const distanceOptions = [0.5, 1, 2, 5, 10, 25, 50, 100];

  // Use refs to access latest values without causing dependency issues
  const dishesRef = useRef<Dish[]>([]);
  const userLocationRef = useRef<{ latitude: number; longitude: number; name?: string } | null>(null);

  // Keep refs in sync with state
  useEffect(() => {
    dishesRef.current = dishes;
  }, [dishes]);

  useEffect(() => {
    userLocationRef.current = userLocation;
  }, [userLocation]);

  const router = useRouter();
  const { favoriteIds, toggleFavorite } = useFavorites();

  useEffect(() => {
    // Load dishes on initial mount
    setHasInitiatedSearch(true);
    loadDishes({ query: '' });
    loadUserLocation();
  }, []);

  // Close distance dropdown when tapping outside
  useEffect(() => {
    if (showDistanceDropdown) {
      const timer = setTimeout(() => setShowDistanceDropdown(false), 3000); // Auto-close after 3 seconds
      return () => clearTimeout(timer);
    }
  }, [showDistanceDropdown]);

  // Load saved location or request permission
  const loadUserLocation = useCallback(async () => {
    try {
      // Check if we have saved location
      const savedLocation = await AsyncStorage.getItem('userLocation');
      if (savedLocation) {
        const locationData = JSON.parse(savedLocation);
        setUserLocation(locationData);
        setLocationPermission('granted');
      return;
    }

      // Request location permission
      const { status } = await Location.requestForegroundPermissionsAsync();
      setLocationPermission(status);

      if (status === 'granted') {
        const location = await Location.getCurrentPositionAsync({});
        const coords = {
          latitude: location.coords.latitude,
          longitude: location.coords.longitude,
          name: 'Current Location'
        };
        setUserLocation(coords);
        await AsyncStorage.setItem('userLocation', JSON.stringify(coords));
      }
    } catch (error) {
      console.error('Error getting location:', error);
    }
  }, []);

  // Handle manual location search
  const handleLocationSearch = useCallback(async () => {
    if (!manualLocation.trim()) return;

    try {
      const geocode = await Location.geocodeAsync(manualLocation.trim());
      if (geocode.length > 0) {
        const location = geocode[0];
        const coords = {
          latitude: location.latitude,
          longitude: location.longitude,
          name: manualLocation.trim()
        };
        setUserLocation(coords);
        setManualLocation('');
        setShowLocationInput(false);
        await AsyncStorage.setItem('userLocation', JSON.stringify(coords));
        // Reload dishes with new location
        loadDishes({ query: activeQuery });
      } else {
        Alert.alert('Location not found', 'Please try a different location name.');
      }
    } catch (error) {
      console.error('Error geocoding location:', error);
      Alert.alert('Error', 'Unable to find that location. Please try again.');
    }
  }, [manualLocation, activeQuery, loadDishes]);

  const loadDishes = useCallback(
    async (overrides?: { cuisine?: string; query?: string; preserveExisting?: boolean }) => {
      if (!hasInitiatedSearch && !overrides) {
        return;
      }

    setIsLoading(true);
      if (!overrides?.preserveExisting) {
    setDishes([]);
      }

      const queryFilter = overrides?.query ?? activeQuery;

    try {
      // Load dishes first
      // Filter out pending or rejected dishes by default, only show approved
      let query = supabase.from('dishes')
        .select('*')
        .or('review_status.eq.approved,review_status.eq.pending'); // Allow pending for now until review process is mature
        // In future: .eq('review_status', 'approved');

      if (queryFilter) {
        const sanitized = queryFilter.replace(/[%_]/g, '').trim();
        if (sanitized) {
          const pattern = `%${sanitized}%`;
          query = query.ilike('cuisine_type', pattern);
        }
      }

      const { data: dishesData, error: dishesError } = await query;

      if (dishesError) {
        console.error('[FoodFinder] Error loading dishes:', dishesError);
        console.error('[FoodFinder] Error details:', JSON.stringify(dishesError, null, 2));
        Alert.alert('Error', `Failed to load dishes: ${dishesError.message || 'Unknown error'}`);
        return;
      }

      // Get unique restaurant IDs
      const restaurantIds = [...new Set((dishesData || []).map(dish => dish.restaurant_id).filter(Boolean))];

      // Load restaurant data separately
      let restaurantsData = {};
      if (restaurantIds.length > 0) {
        const { data: restData, error: restError } = await supabase
          .from('restaurants')
          .select('id, name, latitude, longitude')
          .in('id', restaurantIds);

        if (restError) {
          console.error('Error loading restaurants:', restError);
        } else {
          restaurantsData = restData?.reduce((acc, rest) => {
            acc[rest.id] = rest;
            return acc;
          }, {}) || {};
        }
      }

      // Merge restaurant data into dishes
      const data = (dishesData || []).map(dish => ({
        ...dish,
        restaurants: restaurantsData[dish.restaurant_id] || null
      }));

      // Use user's location or fallback to Charlottesville, VA
      const currentUserLocation = userLocationRef.current;
      const userLat = currentUserLocation?.latitude ?? 38.0293; // Charlottesville, VA fallback
      const userLng = currentUserLocation?.longitude ?? -78.4767;
      const maxDistanceMiles = searchDistance; // Use selected search distance

      // Check if any restaurants have coordinates for proximity filtering
      const hasCoordinates = (data || []).some((dish: any) =>
        dish.restaurants?.latitude && dish.restaurants?.longitude
      );

      let formattedDishes;

      if (!hasCoordinates) {
        // Show all dishes if no coordinates are available (fallback for location permission not granted)
        formattedDishes = (data || []).map((dish: any) => {
          return {
            dishId: dish.id,
            name: dish.name,
            description: dish.description || '',
            imageUrl: imagePublicUrl(dish.image_url),
            restaurant: dish.restaurants?.name || 'Unknown Restaurant',
            price: dish.price,
            cuisineType: dish.cuisine_type || null,
            restaurantId: dish.restaurant_id,
            restaurantData: dish.restaurants, // Keep full restaurant data for proximity filtering
          };
        });
      } else {
        // Filter by proximity and format dishes
        formattedDishes = (data || [])
          .filter((dish: any) => {
            if (!dish.restaurants?.latitude || !dish.restaurants?.longitude) {
              return false; // Skip dishes without restaurant location
            }

            // Calculate distance using Haversine formula
            const lat1 = userLat * Math.PI / 180;
            const lng1 = userLng * Math.PI / 180;
            const lat2 = dish.restaurants.latitude * Math.PI / 180;
            const lng2 = dish.restaurants.longitude * Math.PI / 180;

            const dLat = lat2 - lat1;
            const dLng = lng2 - lng1;

            const a = Math.sin(dLat/2) * Math.sin(dLat/2) +
              Math.cos(lat1) * Math.cos(lat2) *
              Math.sin(dLng/2) * Math.sin(dLng/2);
            const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));

            const distanceMiles = 3959 * c; // Earth radius in miles

            return distanceMiles <= maxDistanceMiles;
          })
          .map((dish: any) => ({
          dishId: dish.id,
          name: dish.name,
          description: dish.description || '',
          imageUrl: imagePublicUrl(dish.image_url),
            restaurant: dish.restaurants?.name || 'Unknown Restaurant',
          price: dish.price,
            cuisineType: dish.cuisine_type || null,
            restaurantId: dish.restaurant_id,
          }));
      }

      // If no dishes in range and we're not preserving, try expanding the range
      if (formattedDishes.length === 0 && !overrides?.preserveExisting && hasCoordinates) {
        
        // Try progressively larger distances
        const expandedDistances = [10, 25, 50, 100, 500]; // miles
        let foundWithExpanded = false;
        
        for (const expandedDistance of expandedDistances) {
          if (expandedDistance <= maxDistanceMiles) continue; // Skip if already tried
          
          const expandedDishes = (data || [])
            .filter((dish: any) => {
              if (!dish.restaurants?.latitude || !dish.restaurants?.longitude) return false;
              
              const lat1 = userLat * Math.PI / 180;
              const lng1 = userLng * Math.PI / 180;
              const lat2 = dish.restaurants.latitude * Math.PI / 180;
              const lng2 = dish.restaurants.longitude * Math.PI / 180;
              const dLat = lat2 - lat1;
              const dLng = lng2 - lng1;
              const a = Math.sin(dLat/2) * Math.sin(dLat/2) +
                Math.cos(lat1) * Math.cos(lat2) *
                Math.sin(dLng/2) * Math.sin(dLng/2);
              const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
              const distanceMiles = 3959 * c;
              
              return distanceMiles <= expandedDistance;
            })
            .map((dish: any) => ({
          dishId: dish.id,
          name: dish.name,
          description: dish.description || '',
          imageUrl: imagePublicUrl(dish.image_url),
              restaurant: dish.restaurants?.name || 'Unknown Restaurant',
          price: dish.price,
              cuisineType: dish.cuisine_type || null,
              restaurantId: dish.restaurant_id,
            }));
          
          if (expandedDishes.length > 0) {
            formattedDishes = expandedDishes;
            // Update the distance selector to reflect the expanded range
            setSearchDistance(expandedDistance);
            Alert.alert(
              'Distance Expanded', 
              `No dishes found within ${maxDistanceMiles} miles. Showing results within ${expandedDistance} miles instead.`,
              [{ text: 'OK' }]
            );
            foundWithExpanded = true;
            break;
          }
        }
        
        if (!foundWithExpanded && formattedDishes.length === 0) {
          Alert.alert(
            'No Dishes Nearby', 
            'There are no dishes available in your area. Try adjusting your location or check back later.',
            [{ text: 'OK' }]
          );
        }
      }

      // Randomize the order for home screen variety
      formattedDishes = formattedDishes.sort(() => Math.random() - 0.5);

      // Filter out dishes that are already favorited
      formattedDishes = formattedDishes.filter((dish) => !favoriteIds.has(dish.dishId));

      // Filter out dishes that are already in the current view (when preserving)
      if (overrides?.preserveExisting) {
        const currentDishes = dishesRef.current;
        const existingDishIds = new Set(currentDishes.map(d => d.dishId));
        formattedDishes = formattedDishes.filter((dish) => !existingDishIds.has(dish.dishId));
      }

        const normalizedQuery = queryFilter.toLowerCase();
        let filteredDishes = formattedDishes;

        if (queryFilter) {
          filteredDishes = filteredDishes.filter((dish) => {
            const haystack = `${dish.name} ${dish.description} ${dish.cuisineType || ''}`.toLowerCase();
            return haystack.includes(normalizedQuery);
          });
        }

        // If still no dishes after all filters, show helpful message

        // Append or replace dishes
        if (overrides?.preserveExisting) {
          setDishes(prevDishes => [...prevDishes, ...filteredDishes]);
        } else {
          setDishes(filteredDishes);
        }
    } catch (error) {
      console.error('Unexpected error loading dishes:', error);
      Alert.alert('Error', 'Failed to load dishes');
    } finally {
      setIsLoading(false);
        setRefreshing(false);
    }
    },
    [activeQuery, hasInitiatedSearch, searchDistance, favoriteIds]
  );


  const handleSearchSubmit = useCallback(() => {
    const trimmed = searchQuery.trim();
    if (!trimmed) {
      Alert.alert('Search required', 'Type a cuisine or dish to begin swiping.');
      return;
    }

    setActiveQuery(trimmed);
    setHasInitiatedSearch(true);
    loadDishes({ query: trimmed });
  }, [loadDishes, searchQuery]);


  const handleManualReload = useCallback(() => {
    setRefreshing(true);
    loadDishes({ preserveExisting: true });
  }, [loadDishes]);

  const handleResetSearch = useCallback(() => {
    setSearchQuery('');
    setActiveQuery('');
    setHasInitiatedSearch(true);
    loadDishes({ query: '' }); // Load fresh dishes with no filters
  }, [loadDishes]);

  const insets = useSafeAreaInsets();

  const buildFavoriteInput = useCallback(
    (dish: Dish) => ({
      dishId: dish.dishId,
      name: dish.name,
      description: dish.description || '',
      imageUrl: dish.imageUrl,
      price: dish.price ?? null,
      cuisineType: dish.cuisineType ?? null,
      restaurantId: dish.restaurantId || null,
      restaurantName: dish.restaurant,
    }),
    [],
  );

  const handleToggleFavorite = useCallback(
    async (dish: Dish, event?: GestureResponderEvent) => {
      event?.stopPropagation?.();
      
      // Check if we're adding or removing
      const isCurrentlyFavorited = favoriteIds.has(dish.dishId);
      
      // Optimistically remove from UI immediately for snappy UX
      if (!isCurrentlyFavorited) {
        setDishes(prevDishes => prevDishes.filter(d => d.dishId !== dish.dishId));
      }
      
      // Toggle the favorite in the database (async, in background)
      try {
        await toggleFavorite(buildFavoriteInput(dish));
      } catch (error) {
        // If it fails, add the dish back
        if (!isCurrentlyFavorited) {
          console.error('[FoodFinder] Failed to add favorite, restoring dish');
          setDishes(prevDishes => [...prevDishes, dish]);
        }
      }
    },
    [toggleFavorite, buildFavoriteInput, favoriteIds],
  );

  const handleOpenDish = useCallback(
    (dishId: string) => {
      if (!dishId) return;
      router.push(`/dish/${dishId}`);
    },
    [router]
  );

  const handleRefresh = useCallback(() => {
    if (!hasInitiatedSearch) {
      return;
    }
    setRefreshing(true);
    loadDishes({ preserveExisting: true });
  }, [hasInitiatedSearch, loadDishes]);

  // Memoize getItemLayout for better FlatList performance
  const getItemLayout = useCallback((data: any, index: number) => {
    const ITEM_HEIGHT = 316; // Approximate: 240px image + 60px meta + margins
    const rowIndex = Math.floor(index / 2); // 2 columns
    return {
      length: ITEM_HEIGHT,
      offset: ITEM_HEIGHT * rowIndex,
      index,
    };
  }, []);

  const renderDishCard = useCallback(({ item }: { item: Dish }) => {
    const isFavorited = favoriteIds.has(item.dishId);

    const onHandlerStateChange = (event: any) => {
      if (event.nativeEvent.state === State.END) {
        const { translationX, velocityX } = event.nativeEvent;
        const swipeThreshold = 50;
        const velocityThreshold = 500;

        if (Math.abs(translationX) > swipeThreshold && Math.abs(velocityX) > velocityThreshold) {
          if (translationX > 0) {
            handleToggleFavorite(item);
          }
        }
      }
    };

    return (
      <PanGestureHandler onHandlerStateChange={onHandlerStateChange}>
        <TouchableOpacity
          activeOpacity={0.9}
          style={styles.galleryCard}
          onPress={() => handleOpenDish(item.dishId)}
        >
          <View style={styles.imageContainer}>
            <Image
              source={{ uri: item.imageUrl ?? DEFAULT_IMAGE_URL }}
              style={styles.galleryImage}
              resizeMode="cover"
            />
            <View style={styles.overlayContainer}>
        <TouchableOpacity
                style={styles.saveOverlay}
                onPress={(event) => handleToggleFavorite(item, event)}
              >
                <MaterialIcons
                  name="restaurant"
                  size={24}
                  color={isFavorited ? "#4CAF50" : "rgba(255, 255, 255, 0.9)"}
                />
              </TouchableOpacity>
            </View>
          </View>
          <View style={styles.galleryMeta}>
            <View style={styles.galleryHeader}>
              <Text style={styles.galleryRestaurant}>{item.restaurant}</Text>
              {!!item.price && <Text style={styles.galleryPrice}>${item.price.toFixed(2)}</Text>}
            </View>
            {item.cuisineType && (
              <Text style={styles.galleryCuisine}>{item.cuisineType}</Text>
            )}
          </View>
        </TouchableOpacity>
      </PanGestureHandler>
    );
  }, [favoriteIds, handleToggleFavorite, handleOpenDish]);

  const renderSearchBar = () => (
    <View style={[styles.searchContainer, { paddingTop: Math.max(insets.top, 12) }]}>
      {/* Location Button and Distance Selector - moved above search bar */}
      <View style={styles.locationRow}>
        <TouchableOpacity
          style={styles.locationButton}
          onPress={() => {
            // Always show location options menu
            Alert.alert(
              'Set Location',
              'Choose how to set your search location',
              [
                { text: 'Cancel', style: 'cancel' },
                {
                  text: '📍 Use Current Location',
                  onPress: async () => {
                    try {
                      const { status } = await Location.requestForegroundPermissionsAsync();
                      if (status === 'granted') {
                        const location = await Location.getCurrentPositionAsync({});
                        const coords = {
                          latitude: location.coords.latitude,
                          longitude: location.coords.longitude,
                          name: 'Current Location'
                        };
                        setUserLocation(coords);
                        setLocationPermission('granted');
                        await AsyncStorage.setItem('userLocation', JSON.stringify(coords));
                        loadDishes({ query: activeQuery });
                      } else {
                        Alert.alert('Permission denied', 'Location permission is required to find nearby restaurants.');
                      }
                    } catch (error) {
                      Alert.alert('Error', 'Unable to get your location. Please try again.');
                    }
                  }
                },
                {
                  text: '🗺️ Choose on Map',
                  onPress: () => {
                    Alert.alert(
                      'Map Selection',
                      'Map selection feature coming soon! For now, please use "Type in City" or "Use Current Location".',
                      [{ text: 'OK' }]
                    );
                  }
                },
                {
                  text: '🏙️ Type in City',
                  onPress: () => setShowLocationInput(true)
                },
              ]
            );
          }}
        >
          <MaterialIcons
            name={
              locationPermission === 'granted' && userLocation
                ? 'location-on'
                : 'location-off'
            }
            size={16}
            color={
              locationPermission === 'granted' && userLocation
                ? '#4CAF50'
                : '#999'
            }
          />
          <Text style={[
            styles.locationButtonText,
            locationPermission === 'granted' && userLocation && styles.locationButtonTextActive
          ]}>
            {userLocation?.name || 'Set Location'}
          </Text>
        </TouchableOpacity>

        {/* Distance Selector */}
          <TouchableOpacity
          style={styles.distanceButton}
          onPress={() => setShowDistanceDropdown(!showDistanceDropdown)}
        >
          <MaterialIcons name="straighten" size={16} color="#007AFF" />
          <Text style={styles.distanceButtonText}>
            {searchDistance} mi
            </Text>
          <MaterialIcons
            name={showDistanceDropdown ? 'keyboard-arrow-up' : 'keyboard-arrow-down'}
            size={16}
            color="#007AFF"
          />
          </TouchableOpacity>

      </View>

      {/* Search Row */}
      <View style={styles.searchRow}>
        <View style={styles.searchInputWrapper}>
          <TextInput
            style={styles.searchInput}
            placeholder="Search for dishes (e.g. burritos, pizza, sushi)"
            placeholderTextColor="#999"
            value={searchQuery}
            onChangeText={setSearchQuery}
            autoCorrect={false}
            autoCapitalize="none"
            clearButtonMode="while-editing"
            returnKeyType="search"
            onSubmitEditing={handleSearchSubmit}
          />
        </View>
      <TouchableOpacity
          style={[styles.searchButton, !searchQuery.trim() && styles.searchButtonDisabled]}
          onPress={handleSearchSubmit}
          disabled={!searchQuery.trim()}
        >
          <MaterialIcons
            name="search"
            size={20}
            color="#fff"
          />
      </TouchableOpacity>
      </View>

      {/* Manual Location Input Modal */}
      {showLocationInput && (
        <View style={styles.locationInputContainer}>
          <View style={styles.locationInputModal}>
            <Text style={styles.locationInputTitle}>Enter Your Location</Text>
            <TextInput
              style={styles.locationInput}
              placeholder="City, State or Address"
              placeholderTextColor="#999"
              value={manualLocation}
              onChangeText={setManualLocation}
              autoCorrect={false}
              autoCapitalize="words"
              returnKeyType="search"
              onSubmitEditing={handleLocationSearch}
            />
            <View style={styles.locationInputButtons}>
              <TouchableOpacity
                style={[styles.locationInputButton, styles.locationInputCancel]}
                onPress={() => {
                  setShowLocationInput(false);
                  setManualLocation('');
                }}
              >
                <Text style={styles.locationInputCancelText}>Cancel</Text>
          </TouchableOpacity>
      <TouchableOpacity
                style={[styles.locationInputButton, styles.locationInputConfirm, !manualLocation.trim() && styles.locationInputConfirmDisabled]}
                onPress={handleLocationSearch}
                disabled={!manualLocation.trim()}
              >
                <Text style={styles.locationInputConfirmText}>Set Location</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      )}
    </View>
  );



  if (isLoading && dishes.length === 0) {
    return (
      <SafeAreaView style={styles.safeContainer}>
        <View style={styles.galleryContainer}>
          {renderSearchBar()}
          <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#007AFF" />
      </View>
        </View>
      </SafeAreaView>
    );
  }

  if (dishes.length === 0) {
    return (
      <SafeAreaView style={styles.safeContainer}>
        <View style={styles.galleryContainer}>
          {renderSearchBar()}
          <View style={styles.emptyContainer}>
        <Text style={styles.emptyText}>
          {activeQuery 
            ? `No dishes found matching "${activeQuery}".` 
            : 'No dishes found in your area.'}
        </Text>
        <Text style={styles.emptySubtext}>
          Try adjusting your distance or location settings.
        </Text>
        <TouchableOpacity
          style={[styles.newSearchButton, isLoading && styles.reloadButtonDisabled]}
          onPress={handleResetSearch}
          disabled={isLoading}
        >
          <MaterialIcons name="refresh" size={20} color="#fff" style={{ marginRight: 8 }} />
          <Text style={styles.newSearchButtonText}>
            {isLoading ? 'Loading...' : 'New Search'}
          </Text>
        </TouchableOpacity>
      </View>
      </View>
      </SafeAreaView>
    );
  }

    return (
    <SafeAreaView style={styles.safeContainer}>
      <View style={styles.galleryContainer}>
        {renderSearchBar()}
        <FlatList
          data={dishes}
          keyExtractor={(item) => item.dishId}
          renderItem={renderDishCard}
          numColumns={2}
          columnWrapperStyle={styles.galleryColumn}
          contentContainerStyle={styles.galleryList}
          getItemLayout={getItemLayout}
          removeClippedSubviews={true}
          maxToRenderPerBatch={10}
          updateCellsBatchingPeriod={50}
          windowSize={10}
          initialNumToRender={10}
          refreshControl={
            <RefreshControl refreshing={refreshing} onRefresh={handleRefresh} tintColor="#007AFF" />
          }
          ListFooterComponent={
        <TouchableOpacity
          style={[styles.reloadButton, isLoading && styles.reloadButtonDisabled]}
          onPress={handleManualReload}
          disabled={isLoading}
        >
              <Text style={styles.reloadButtonText}>
                {isLoading ? 'Loading...' : 'Load More Dishes'}
              </Text>
        </TouchableOpacity>
          }
        />
        <TouchableOpacity style={styles.resetButton} onPress={handleResetSearch}>
          <Text style={styles.resetButtonText}>New Search</Text>
        </TouchableOpacity>
          </View>

      {/* Distance Dropdown - positioned outside container for proper z-index */}
      {showDistanceDropdown && (
        <View style={styles.distanceDropdownOverlay}>
          <ScrollView
            style={{ maxHeight: 200 }}
            showsVerticalScrollIndicator={false}
            bounces={false}
          >
            {distanceOptions.map((distance) => (
              <TouchableOpacity
                key={distance}
                style={[
                  styles.distanceOption,
                  searchDistance === distance && styles.distanceOptionActive
                ]}
                onPress={() => {
                  setSearchDistance(distance);
                  setShowDistanceDropdown(false);
                  // Reload dishes with new distance
                  loadDishes({ query: activeQuery });
                }}
              >
                <Text style={[
                  styles.distanceOptionText,
                  searchDistance === distance && styles.distanceOptionTextActive
                ]}>
                  {distance} mile{distance !== 1 ? 's' : ''}
                </Text>
              </TouchableOpacity>
            ))}
          </ScrollView>
      </View>
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  initialContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 20 : 24,
  },
  galleryContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'ios' ? 20 : 24,
  },
  galleryList: {
    paddingTop: 8,
    paddingBottom: 40,
  },
  galleryColumn: {
    gap: 8, // Reduced from 12px for sleeker feel
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 50,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 50,
  },
  galleryCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 20, // Slightly more rounded for modern feel
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.06, // Subtle shadow for sleek look
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    marginHorizontal: 4, // Reduced from 6px for tighter spacing
  },
  imageContainer: {
    position: 'relative',
  },
  galleryImage: {
    width: '100%',
    height: 240, // Increased from 220px to make images more prominent
    resizeMode: 'cover', // Ensure images fill the space nicely
  },
  overlayContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  saveOverlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 20,
    padding: 8,
    margin: 8,
  },
  galleryMeta: {
    padding: 10, // Reduced from 12px for tighter spacing
    gap: 4, // Reduced gap for more compact feel
  },
  galleryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  galleryRestaurant: {
    fontSize: 11, // Slightly smaller for sleeker look
    fontWeight: '500',
    color: '#666', // Darker for better contrast
    flex: 1,
  },
  galleryPrice: {
    fontSize: 13, // Slightly smaller
    fontWeight: '600',
    color: '#333', // Darker for better readability
  },
  galleryCuisine: {
    fontSize: 12,
    color: '#777',
    textTransform: 'capitalize',
  },
  galleryActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
  },
  saveButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 20,
    padding: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  searchContainer: {
    width: '100%',
    marginBottom: 16,
  },
  locationRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 8,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInputWrapper: {
    flex: 1,
  },
  searchInput: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  searchButton: {
    marginLeft: 12,
    backgroundColor: '#007AFF',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchButtonDisabled: {
    opacity: 0.5,
  },
  // Location button styles
  locationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#007AFF',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  locationButtonText: {
    color: '#007AFF',
    fontSize: 12,
    fontWeight: '500',
  },
  locationButtonTextActive: {
    color: '#4CAF50',
  },
  // Distance button styles
  distanceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#007AFF',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#fff',
    marginLeft: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  distanceButtonText: {
    color: '#007AFF',
    fontSize: 12,
    fontWeight: '500',
  },
  distanceDropdownOverlay: {
    position: 'absolute',
    top: 120, // Fixed position below search bar area
    right: 20, // Align to right edge
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 10,
    zIndex: 1000,
    minWidth: 120,
    maxWidth: 150,
  },
  distanceOption: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  distanceOptionActive: {
    backgroundColor: '#f8f9ff',
  },
  distanceOptionText: {
    color: '#333',
    fontSize: 14,
    fontWeight: '500',
  },
  distanceOptionTextActive: {
    color: '#007AFF',
    fontWeight: '600',
  },
  // Location input modal styles
  locationInputContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  locationInputModal: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    width: '85%',
    maxWidth: 400,
  },
  locationInputTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#222',
    marginBottom: 16,
    textAlign: 'center',
  },
  locationInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 20,
  },
  locationInputButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  locationInputButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  locationInputCancel: {
    backgroundColor: '#f5f5f5',
  },
  locationInputCancelText: {
    color: '#666',
    fontWeight: '600',
  },
  locationInputConfirm: {
    backgroundColor: '#007AFF',
  },
  locationInputConfirmDisabled: {
    backgroundColor: '#ccc',
  },
  locationInputConfirmText: {
    color: '#fff',
    fontWeight: '600',
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
  },
  newSearchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 14,
    backgroundColor: '#007AFF',
    borderRadius: 30,
    marginTop: 16,
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  newSearchButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  refreshButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#007AFF',
    borderRadius: 20,
    marginLeft: 10,
  },
  refreshButtonDisabled: {
    opacity: 0.6,
  },
  refreshButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  reloadButton: {
    marginTop: 20,
    backgroundColor: '#007AFF',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
    alignSelf: 'center',
    marginBottom: 16,
  },
  reloadButtonDisabled: {
    opacity: 0.6,
  },
  reloadButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  resetButton: {
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#007AFF',
    alignSelf: 'center',
  },
  resetButtonText: {
    color: '#007AFF',
    fontWeight: '600',
  },
});